# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "prowlr"
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rob Bevan"]
  s.date = "2013-06-24"
  s.email = "robbevan@xpt.com"
  s.executables = ["prowlr"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/prowlr",
    "examples/add.rb",
    "examples/add_instance.rb",
    "examples/helpers/config_store.rb",
    "examples/remaining_calls.rb",
    "examples/reset_date.rb",
    "examples/valid_apikey.rb",
    "examples/verify.rb",
    "lib/prowlr.rb",
    "prowlr.gemspec",
    "test/fixtures/bad_request.xml",
    "test/fixtures/invalid_apikey.xml",
    "test/fixtures/success.xml",
    "test/prowlr_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/robbevan/prowlr"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Yet another Prowl API gem and command line interface"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0"])
  end
end

